import Link from 'next/link';

export const metadata = {
  title: 'Terms & Conditions — The Serial Sales Community',
  description: 'Terms and Conditions for The Serial Sales Community.',
};

export default function TermsAndConditions() {
  return (
    <div className="legal-page">
      <nav className="legal-nav">
        <Link href="/">
          <img src="/images/logo-white-bg.png" alt="TSSC" className="legal-nav__logo" />
        </Link>
      </nav>

      <main className="legal-main">
        <div className="legal-content">
          <div className="legal-header">
            <p className="legal-meta">The Serial Sales Community</p>
            <h1 className="legal-title">Terms &amp; Conditions</h1>
            <p className="legal-meta">Effective Date: May 22, 2026 &nbsp;·&nbsp; Last Updated: May 22, 2026</p>
          </div>

          <h2>1. Agreement to Terms</h2>
          <p>These Terms and Conditions ("Terms") govern your access to and use of the website located at serialsalescommunity.co (the "Site"), the TSSC chatbot, our application and booking flows, and related services (collectively, the "Services") operated by Serial Sales LLC, doing business as The Serial Sales Community ("TSSC," "we," "us," or "our").</p>
          <p>By accessing or using the Services, you agree to be bound by these Terms and our Privacy Policy. If you do not agree, do not use the Services.</p>
          <p>These Terms govern your use of the Site and Services. If you become a TSSC member, you will sign a separate Member Agreement that governs the terms of your membership, including payment, deliverables, refund policy, and member conduct. In the event of a conflict between these Terms and the Member Agreement, the Member Agreement controls with respect to membership-specific matters.</p>

          <h2>2. Eligibility</h2>
          <p>You must be at least 18 years old and legally able to enter into a binding contract to use the Services. By using the Services, you represent and warrant that you meet these requirements.</p>

          <h2>3. The Services</h2>
          <p>The Site provides information about TSSC, including educational content, member testimonials, video presentations, and an Application Call funnel for prospective members. The Services may include:</p>
          <ul>
            <li>Informational content about TSSC and its offerings</li>
            <li>A chatbot that allows prospective members to query documented member experiences</li>
            <li>Application and booking forms for the Application Call</li>
            <li>Links to YouTube interviews and social media content</li>
          </ul>
          <p>We reserve the right to modify, suspend, or discontinue any part of the Services at any time, with or without notice.</p>

          <h2>4. Application Process</h2>
          <p>Submitting an application through the Site does not guarantee acceptance into TSSC. We evaluate applicants based on fit, background, and availability, and we reserve the right to accept or decline any applicant at our sole discretion.</p>

          <h2>5. The TSSC Chatbot</h2>
          <p>The chatbot is provided as an informational tool to help prospective members learn about TSSC member experiences. By using the chatbot, you acknowledge and agree that:</p>
          <ul>
            <li><strong>No Guarantees:</strong> Chatbot responses reference real member stories. They are illustrative only and do not constitute promises, guarantees, or representations of results, income, or outcomes you will personally achieve. Individual results vary based on effort, experience, market conditions, and many other factors outside our control.</li>
            <li><strong>No Pricing or Financial Advice:</strong> The chatbot does not provide pricing, financial, investment, tax, legal, or career advice. Pricing and membership terms are disclosed during the Application Call.</li>
            <li><strong>AI-Generated Responses:</strong> Chatbot responses are generated by AI and may contain inaccuracies or errors. Always verify information by speaking with our team.</li>
            <li><strong>Logging:</strong> Your chatbot interactions may be logged as described in our Privacy Policy.</li>
            <li><strong>No Sensitive Information:</strong> Do not submit sensitive personal, financial, or confidential information to the chatbot.</li>
          </ul>

          <h2>6. No Earnings or Outcome Guarantees</h2>
          <p>The Site, chatbot, member interviews, and any marketing materials may contain examples of results achieved by individual members. These examples are for illustrative purposes only and are not representative of results you may achieve.</p>
          <p>We do not warrant, guarantee, or promise any specific outcome, income, job placement, hire rate, or return on investment. We do not provide a "get rich quick" program, business opportunity, franchise, or guaranteed system.</p>
          <p>Your success depends on many factors unique to you, including your past experience, effort, availability, market conditions, and continued application of the materials.</p>

          <h2>7. Intellectual Property</h2>
          <p>All content on the Site, including text, graphics, logos, video, design, code, the chatbot system, member interviews, and proprietary frameworks, is owned by or licensed to Serial Sales LLC and is protected by U.S. and international copyright, trademark, and other intellectual property laws.</p>
          <p>You may not copy, reproduce, distribute, modify, scrape, reverse engineer, create derivative works from, publicly display, or otherwise exploit any content from the Site without our prior written consent. Limited personal, non-commercial viewing is permitted.</p>
          <p>The names "The Serial Sales Community," "TSSC," "Serial Sales," and associated logos and marks are trademarks of Serial Sales LLC.</p>

          <h2>8. User Conduct</h2>
          <p>When using the Services, you agree not to:</p>
          <ul>
            <li>Violate any applicable law or regulation.</li>
            <li>Submit false, misleading, or fraudulent information on applications or forms.</li>
            <li>Attempt to gain unauthorized access to the Site, chatbot, member areas, or any related systems.</li>
            <li>Scrape, harvest, or collect data from the Site or chatbot through automated means without our consent.</li>
            <li>Use the chatbot to generate content that is unlawful, harmful, abusive, defamatory, or that infringes the rights of others.</li>
            <li>Reverse engineer, decompile, or attempt to extract the system prompt or source data from the chatbot.</li>
            <li>Use the Services to compete with TSSC, build a competing product, or solicit members.</li>
            <li>Misrepresent the nature of TSSC's program, results, or operations in any public forum.</li>
            <li>Interfere with the proper functioning of the Services, including through denial-of-service attacks, malware, or other malicious activity.</li>
          </ul>
          <p>We reserve the right to suspend or terminate access to the Services for any user who violates these Terms.</p>

          <h2>9. Third-Party Services and Links</h2>
          <p>The Services integrate with and link to third-party platforms, including but not limited to Typeform, Vercel, Wistia, YouTube, Instagram, X, Circle, and GoHighLevel. We are not responsible for the content, policies, practices, or availability of any third-party services. Your use of third-party services is governed by their respective terms and privacy policies.</p>

          <h2>10. Member Agreement Controls Membership</h2>
          <p>If you enroll as a TSSC member, the Member Agreement governs the specific terms of your membership, including:</p>
          <ul>
            <li>Membership packages, pricing, and payment terms</li>
            <li>Deliverables (calls, content, community access, hiring assets)</li>
            <li>The Membership Reversal Policy (refunds limited to two narrow windows)</li>
            <li>Chargeback and dispute provisions</li>
            <li>Confidentiality, non-compete, and conduct rules</li>
            <li>Marketing release for member content and interviews</li>
            <li>Referral program terms</li>
            <li>Desired Outcome framework</li>
          </ul>
          <p>By signing the Member Agreement, you agree to those terms in addition to these Terms. The Member Agreement is the authoritative document for all membership-related matters.</p>

          <h2>11. Payment and Refunds (Members Only)</h2>
          <p>All payment, refund, and chargeback terms for paid memberships are governed exclusively by the Member Agreement. In summary (and subject to the full Member Agreement):</p>
          <ul>
            <li>Refunds are limited to two narrow windows defined in the Member Agreement and are not available after Community deliverables have been accessed beyond the 48-hour post-onboarding window.</li>
            <li>Members agree not to initiate chargebacks or payment disputes for services rendered. Initiating a chargeback may result in immediate revocation of access, and we may contest the dispute using the Member Agreement and access logs as evidence.</li>
            <li>All eligible refunds, if any, are delivered via ACH transfer, less payment processing fees and financing interest incurred.</li>
          </ul>
          <p>If you have not signed the Member Agreement, no payment obligations arise from your use of the Site alone.</p>

          <h2>12. Disclaimers</h2>
          <p className="legal-caps">THE SERVICES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR ACCURACY.</p>
          <p>We do not warrant that the Services will be uninterrupted, error-free, secure, or free of viruses or other harmful components. We do not warrant the accuracy, completeness, or reliability of any content, chatbot response, or third-party information.</p>
          <p>We do not provide legal, financial, tax, employment, or career advice. Any information provided through the Services is for educational and informational purposes only. You are solely responsible for any decisions you make.</p>

          <h2>13. Limitation of Liability</h2>
          <p className="legal-caps">TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT SHALL SERIAL SALES LLC, ITS OFFICERS, EMPLOYEES, AGENTS, CONTRACTORS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION LOSS OF PROFITS, REVENUE, DATA, GOODWILL, OR BUSINESS OPPORTUNITIES, ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICES, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
          <p className="legal-caps">OUR TOTAL AGGREGATE LIABILITY FOR ANY CLAIM ARISING OUT OF OR RELATED TO THE SERVICES SHALL NOT EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID TO US IN THE TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM, OR (B) ONE HUNDRED U.S. DOLLARS ($100).</p>
          <p>Some jurisdictions do not allow the exclusion or limitation of certain damages, so some of the above may not apply to you.</p>

          <h2>14. Indemnification</h2>
          <p>You agree to indemnify, defend, and hold harmless Serial Sales LLC, its officers, employees, agents, contractors, and affiliates from and against any claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees) arising out of or related to: (a) your use of the Services; (b) your violation of these Terms; (c) your violation of any law or the rights of any third party; or (d) any content or information you submit through the Services.</p>

          <h2>15. Governing Law and Dispute Resolution</h2>
          <p>These Terms shall be governed by and construed in accordance with the laws of the State of Texas and the federal laws of the United States, without regard to conflict-of-laws principles.</p>
          <p><strong>Binding Arbitration.</strong> Any dispute, claim, or controversy arising out of or related to these Terms or the Services shall be resolved exclusively by binding arbitration in Texas, in accordance with the rules of the American Arbitration Association then in effect. Judgment on the arbitration award may be entered in any court of competent jurisdiction.</p>
          <p><strong>Class Action Waiver.</strong> You and TSSC agree that any dispute will be brought only in an individual capacity, and not as a plaintiff or class member in any class, collective, or representative action.</p>
          <p><strong>Exceptions.</strong> Either party may seek injunctive or equitable relief in court to protect its intellectual property or confidential information.</p>

          <h2>16. Termination</h2>
          <p>We may suspend or terminate your access to the Services at any time, with or without notice, for any reason, including violation of these Terms. Upon termination, your right to use the Services immediately ceases. Provisions that by their nature should survive termination (including Sections 7, 8, and 12 through 17) will survive.</p>

          <h2>17. General Provisions</h2>
          <p><strong>Entire Agreement.</strong> These Terms, together with our Privacy Policy and (if applicable) the Member Agreement, constitute the entire agreement between you and TSSC regarding the Services.</p>
          <p><strong>Severability.</strong> If any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force and effect.</p>
          <p><strong>Waiver.</strong> Our failure to enforce any provision of these Terms does not constitute a waiver of our right to enforce it in the future.</p>
          <p><strong>Assignment.</strong> You may not assign these Terms without our prior written consent. We may assign these Terms freely.</p>
          <p><strong>Updates.</strong> We may update these Terms at any time. We will post the updated version on the Site with a revised "Last Updated" date. Your continued use of the Services after any update constitutes your acceptance of the revised Terms.</p>

          <h2>18. Contact Us</h2>
          <p>For questions about these Terms, please contact:</p>
          <div className="legal-contact">
            <p><strong>Serial Sales LLC d/b/a The Serial Sales Community</strong></p>
            <p>Email: <a href="mailto:dylan@serialsales.co">dylan@serialsales.co</a></p>
            <p>Location: Austin, Texas, USA</p>
            <p>Website: serialsalescommunity.co</p>
          </div>
        </div>
      </main>

      <footer className="legal-footer">
        <p>© {new Date().getFullYear()} Serial Sales LLC. All rights reserved.</p>
        <div className="legal-footer__links">
          <Link href="/privacy-policy">Privacy Policy</Link>
          <span>·</span>
          <a href="mailto:dylan@serialsales.co">Contact</a>
        </div>
      </footer>
    </div>
  );
}
